### ISSUE TITLE
Consumer gets stuck out of group, keeps consuming

### ISSUE THREAD

**Issue by braedon** [dpkp/kafka-python#1547]
We're regularly experiencing a pretty severe issue where a consumer seems to get stuck outside of the consumer group - it just stops trying to rejoin. That's bad enough in itself - we gradually lose consumers from the group, and have to restart them - but the consumer actually keeps consuming, despite not being in the group!

Presumably (haven't explicitly checked) a live consumer picks up zombie consumer's partitions when it fails to rejoin the group, causing messages to be consumed multiple times simultaneously.

I've spent quite a few hours trying to trace down the cause of this, but haven't had any luck so far de-tangling exactly what's happening. I've also looked at a bunch of similar outstanding issues, but can't find one that seems to match closely enough to what we're seeing.

Our consumers use `.poll()` (not the iterator), use auto committing, and kafka-python 1.4.3. Our Kafka cluster us running Kafka 1.1.0. We had what seemed to be the same issue under Kafka 0.10.1.0 and kafka-python 1.4.2 - upgrading didn't seem to help.

Here's some logs from an example case:
```
...
July 17th 2018, 15:52:04.270 9,405,227 WARNING consumer-group-heartbeat Heartbeat session expired, marking coordinator dead
July 17th 2018, 15:52:04.270 9,406,379 WARNING consumer-group-heartbeat Marking the coordinator dead (node 0) for group consumer-group: Heartbeat session expired.
July 17th 2018, 15:52:04.311 9,579,684 INFO MainThread Group coordinator for consumer-group is BrokerMetadata(nodeId=2, host='kafka-2', port=9092, rack=None)
July 17th 2018, 15:52:04.311 9,580,669 INFO MainThread Discovered coordinator 2 for group consumer-group
July 17th 2018, 15:52:07.345 9,851,126 WARNING consumer-group-heartbeat Heartbeat: local member_id was not recognized; this consumer needs to re-join
July 17th 2018, 15:52:12.809 9,979,136 ERROR MainThread Offset commit failed: This is likely to cause duplicate message delivery
July 17th 2018, 15:52:12.810 9,980,348 INFO MainThread Revoking previously assigned partitions {TopicPartition(topic='topic', partition=2)} for group consumer-group
July 17th 2018, 15:52:12.810 9,981,257 INFO MainThread (Re-)joining group consumer-group
July 17th 2018, 15:52:13.963 9,997,351 WARNING MainThread Marking the coordinator dead (node 2) for group consumer-group: [Error 16] NotCoordinatorForGroupError.
July 17th 2018, 15:52:16.835 27,741 WARNING MainThread Auto offset commit failed for group consumer-group: [Error 16] NotCoordinatorForGroupError: consumer-group
July 17th 2018, 15:52:16.835 28,996 WARNING MainThread Auto offset commit failed for group consumer-group: [Error 16] NotCoordinatorForGroupError: consumer-group
July 17th 2018, 15:52:16.835 30,251 WARNING MainThread Auto offset commit failed for group consumer-group: [Error 16] NotCoordinatorForGroupError: consumer-group
July 17th 2018, 15:52:16.839 40,506 INFO MainThread Group coordinator for consumer-group is BrokerMetadata(nodeId=2, host='kafka-2', port=9092, rack=None)
July 17th 2018, 15:52:16.839 41,490 INFO MainThread Discovered coordinator 2 for group consumer-group
July 17th 2018, 15:52:18.094 1,040,396 WARNING MainThread Auto offset commit failed for group consumer-group: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
            
July 17th 2018, 15:52:22.693 2,631,080 WARNING MainThread Auto offset commit failed for group consumer-group: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
...
```

The `CommitFailedError`s continue indefinitely. The consumer keeps consuming partition 2 throughout, and indefinitely afterwards as well. I haven't spotted any further attempt to rejoin or heartbeat.

I do have debug logs for this period, but they're too verbose to post here. If it'd help for me to look for something specific in them, let me know.

Any help with this would be appreciated.

**Comment by yangl326-Dylan** [comment]
i get the same issume, and not know how to fix it

**Comment by j2gg0s** [comment]
In my opinion:

- We don't clear subscription after heart failed.
- Maybe because we don't check consumer should rejoin before fetch record in ``poll``.
- This is a bug?

@dpkp

**Comment by dpkp** [comment]
There was a major consumer deadlock bug fix released in 1.4.4. It could be the source of the issue, but I'm confused because a deadlock would prevent further consumption. So it would explain the consumers getting stuck and needing a restart, but it would not explain the consumer continuing to process messages out-of-group.

One very strange thing in these logs is that the group coordinator is found and then marked dead very quickly:

```
July 17th 2018, 15:52:04.311 9,579,684 INFO MainThread Group coordinator for consumer-group is BrokerMetadata(nodeId=2, host='kafka-2', port=9092, rack=None)
July 17th 2018, 15:52:04.311 9,580,669 INFO MainThread Discovered coordinator 2 for group consumer-group
July 17th 2018, 15:52:13.963 9,997,351 WARNING MainThread Marking the coordinator dead (node 2) for group consumer-group: [Error 16] NotCoordinatorForGroupError.
```

If this is happening repeatedly, then it suggests maybe there is also something wrong at the broker level. I can't think of a good explanation of why this would happen other than something like broker split-brain.

**Comment by jeffwidman** [comment]
@braedon was this solved by `1.4.6`?

**Comment by braedon** [comment]
@jeffwidman I haven't spotted this issue for a while, but it's not something I know how to reproduce, unfortunately. Most of our services are still on 1.4.3/1.4.4 TBH.

Unless someone else if actively getting this issue and can test 1.4.6 (@yangl326-Dylan ?), or @j2gg0s is right about needing to check if the consumer needs to rejoin before fetching more records, this can probably be closed. I can re-open it if I see the issue again.

**Comment by jeffwidman** [comment]
Okay, closing, let's definitely re-open if seen again

**Comment by mavemuri** [comment]
Hello, 
we are still seeing this in 2.0.2
I am not familiar with the project so please correct me as needed- 

From what i could gather, [this is the issue](https://github.com/dpkp/kafka-python/blob/2.0.2/kafka/coordinator/base.py#L309) - why would ```self.failed = e``` not be set for ```ReferenceError```? execution path moves on anyway if thats thrown 
Unsure why this issue isn't seen much more frequently if above is true

**Comment by 123mw123** [comment]
I also came across this error recently with kafka-python==2.0.2. Consumer is exiting inference group and keeps consuming But it's eventually rejoining the group

![image](https://user-images.githubusercontent.com/25078260/233606056-e935d0d4-3c8d-4a5e-bab2-89481d8b4b86.png)
